name: Docker Build push

on: 
  push:
    branches:
      - main
    tags:
      - '**' # Trigger on tag
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


env:
  GIT_REF: ${{ github.head_ref || github.ref_name }}
  DOCKER_REGISTRY: ${{ secrets.DOCKER_URL }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GITHUB_PAT: ${{ secrets.GIT_PAT }}
  DOCKER_IMAGE_NAME: registry.digitalocean.com/karpatkey/${{ github.event.repository.name }} 
  DOCKERFILE: './Dockerfile'


jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image using composite action
        uses: karpatkey/build-actions/build-docker-image@main
